package models;

//Generated by Liubisheng
import java.io.Serializable;

import play.cache.Cache;
import play.mvc.Scope;
import controllers.LearnmoreSecurity;

public class CurrentUser implements Serializable{
	
	public Long id;
	public String name;
	public String role;
	public Long domainid;	
	public String domainname;
	public String password;
	
	public CurrentUser(long id, String name, String role,String password){
		this.id = id;
		this.name = name;
		this.role = role;
		this.password=password;
		
	}
	
	public void setDomain(Long domainid, String domainname){
		this.domainid = domainid;
		this.domainname = domainname;		
	}
	
	public static boolean isAuthed(){
		return LearnmoreSecurity.isConnected();
	}
	
	public static CurrentUser current(){
		return (CurrentUser)LearnmoreSecurity.connected();
	}
	
	public String toString(){
		return this.name;
	}
	
	public boolean isSuper(){
		return "root".equals(this.role);
	}
	
	public void set(String key,Object obj){
		Cache.set(Scope.Session.current().getId()+key, obj);
	}
	
	public Object get(String key,Object obj){
		return Cache.get(Scope.Session.current().getId()+key);
	}
	
	public void delete(String key){
		Cache.delete(Scope.Session.current().getId()+key);	
	}
	public String getUsername(){
	    return this.name == null?"":this.name;
	}
	
}


